### ISSUE TITLE
npm install error: installing chromium on arm64 based MacOS

### ISSUE THREAD

**Issue by KevinRickard** [jaydlawrence/stock-checker#6]
Environment:
MacOS 12.2
Macbook Pro 2021 16 inch with M1 Pro
npm 8.6.0

While running `npm install`
```    
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated puppeteer@7.0.4: Version no longer supported. Upgrade to @latest
npm ERR! code 1
npm ERR! path /Users/kevin/Projects/stock-checker-fanatec-dd/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! The chromium binary is not available for arm64.
npm ERR! If you are on Ubuntu, you can install with: 
npm ERR! 
npm ERR!  sudo apt install chromium
npm ERR! 
npm ERR! 
npm ERR!  sudo apt install chromium-browser
npm ERR! 
npm ERR! /Users/kevin/Projects/stock-checker-fanatec-dd/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:115
npm ERR!                     throw new Error();
npm ERR!                     ^
npm ERR! 
npm ERR! Error
npm ERR!     at /Users/kevin/Projects/stock-checker-fanatec-dd/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:115:27
npm ERR!     at FSReqCallback.oncomplete (node:fs:203:21)
npm ERR! 
npm ERR! Node.js v18.0.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kevin/.npm/_logs/2022-05-17T22_02_14_849Z-debug-0.log
```

**Comment by KevinRickard** [comment]
Followed these instructions: https://linguinecode.com/post/how-to-fix-m1-mac-puppeteer-chromium-arm64-bug
  * Had to do `brew install chromium && xattr -cr /Applications/Chromium.app` to install chromium, is different from what that page says, and then carried on. The important part was:

```
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=`which chromium`
```

Now the install works!

**Comment by KevinRickard** [comment]
When testing with `npx check-stock` now getting the following

```
❯ npx check-stock
/Users/kevin/Projects/stock-checker-fanatec-dd/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193
            reject(new Error([
                   ^

Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/Users/kevin/Projects/stock-checker-fanatec-dd/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (/Users/kevin/Projects/stock-checker-fanatec-dd/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.0.0
```

Running `which chromium` shows it should be using a different chromium
```
/opt/homebrew/bin/chromium
```

So I set the executable path in bin/index.js:
```
  let launchOptions = {
    headless: false,
    executablePath: '/opt/homebrew/bin/chromium',
  };
  if (config && config.runHeadless) {
    launchOptions = {
      headless: true,
      args: ['--no-sandbox'],
      executablePath: '/opt/homebrew/bin/chromium',
    };
  }
```

And now it appears to work!
